identifier: kad2o0z256c3k094
allowErrorCollect: true
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: StaticAngularBlog
homeFolder: /home/cperko/code/staticangularblog
distFolder: dist/StaticAngularBlog
outDir: /home/cperko/code/staticangularblog/dist/static
handle404: ''
