identifier: kad2o0z256c3k094
allowErrorCollect: true
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: StaticAngularBlog
homeFolder: C:\Users\chris\code\StaticAngularBlog
distFolder: dist/StaticAngularBlog
outDir: C:\Users\chris\code\StaticAngularBlog\dist\static
handle404: ''
